---
title: "Caissa Data Pre-Processing"
output: html_notebook
---

# === Load Libraries ===

```{r}
library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)
```

# === Load Dataset ===

```{r}
chessgames <- read.csv(file = "./data/Sept_20_analysis.csv")
```

# === Data Exploration ===

```{r}
str(chessgames)
```

```{r}
chessgames %>% 
  group_by(Game_type) %>%
  count()
```

# === Data Pre-Processing ===

```{r}
## Restrict to only blitz games i.e. most popular game type for casual players
blitzgames <- chessgames %>%
  filter(Game_type == "Blitz")

## Remove incomplete records
blitzgames <- blitzgames[complete.cases(blitzgames),]

## Convert date and time columns to correct formats
blitzgames$Date <- as.Date(blitzgames$Date, format = "%Y.%m.%d")
blitzgames$UTCTime <- hms::as_hms(blitzgames$UTCTime)

## Remove GAME field, duplicate records; add customer game_id field and player_moves field
blitzgames <- subset(blitzgames, select = -GAME ) %>%
  distinct() %>%
  tibble::rowid_to_column("game_id") %>%
  mutate(player_moves = ceiling(Total_moves / 2))
```

# === Output Pre-Processed File ===

```{r}
## Save pre-processed data to a new .RDS file which can be used in Shiny app
saveRDS(blitzgames, file = "./data/blitzgames_processed.RDS" )
```



